window.PROGRESS = {
  phase: 'M1 메모리 공격(R2~) · M-UI 디자인 리뉴얼 · A/B 하네스 (3갈래 병렬)',
  note: 'M3 게이트 통과 · M1은 메모리/콜드스타트 목표 미달로 루프 재가동(레버별 기여도 측정 의무) · 사용자 요청으로 디자인 리뉴얼 조각 신설',
  updatedAt: '2026-08-22 15:10',
  metrics: [
    { name: '★ 멀티 4패널 유휴 WS', unit: 'MB', base: 712.8, new: null, target: '≤356' },
    { name: '★ 멀티 4패널 + 추가 창 2개 WS', unit: 'MB', base: 934.1, new: null, target: '≤467' },
    { name: '★ 4패널 동시 스트리밍 직후 WS', unit: 'MB', base: 1161, new: null, target: '≤580' },
    { name: '★ 창 1개 추가 비용', unit: 'MB', base: 110.7, new: null, target: '≪110' },
    { name: '★ 멀티 스크롤/스트리밍 FPS', unit: 'fps', base: 60, new: null, target: '≥60 · 드랍 0%' },
    { name: '단일 유휴 메모리 (WS 합)', unit: 'MB', base: 428.1, new: 415.6, target: '≤214', pass: false },
    { name: '단일 유휴 메모리 (Private 합)', unit: 'MB', base: 341.4, new: 351.4, target: '≤171', pass: false },
    { name: '콜드 스타트 → 첫 창 (웜 중앙값)', unit: 'ms', base: 336, new: 240, target: '≤168', pass: false },
    { name: '콜드 스타트 → UI 사용 가능', unit: 'ms', base: 422, new: 329, target: '≤211', pass: false },
    { name: '긴 스레드 스크롤 평균 FPS (471항목 전량 렌더)', unit: 'fps', base: 60, new: null, target: '≥60' },
    { name: '스트리밍 중 프레임 드랍 (긴 스레드 위)', unit: '%', base: 0, new: null, target: '0' },
    { name: '전송 → 엔진 busy', unit: 'ms', base: 89, new: null, target: '≤89' },
    { name: '설치 풋프린트', unit: 'MB', base: 650, new: null, target: '대폭 감소' }
  ],
  pieces: [
    { name: 'M0 기준 실측', scope: '2.6.2 수치 박제 (콜드 스타트·메모리·스크롤·스트리밍)', state: 'build' },
    { name: 'M1 아키텍처+셸', scope: 'Tauri 워크스페이스·창 시스템·api 심·렌더러 이식 빌드', state: 'build', round: 1 },
    { name: 'M2 스토리지', scope: 'chats·uiPrefs·profile·api-config 등 저장 도메인', state: 'wait' },
    { name: 'M3 Claude 엔진', scope: 'stream-json 상주 CLI·승인/질문·중단·포크·백그라운드', state: 'build', critic: '와이어 스펙 확보(1563줄, 실검증 2회) → PoC 게이트 실행 중: 승인 왕복 toolUseID·중단 생존·포크·job object 좀비 차단' },
    { name: 'M4 Codex 엔진+버전 관리', scope: 'app-server JSONL·엔진 설치/업데이트', state: 'wait' },
    { name: 'M5 계정 도메인', scope: '로그인·전환·per-chat 격리·한도 조회 (DPAPI)', state: 'wait' },
    { name: 'M6 파일·Git·뷰어', scope: 'fs ops·git 래퍼·HTML 미리보기 스킴·아이콘', state: 'wait' },
    { name: 'M7 LSP', scope: 'TS/Py/C#/C++/Verse 서버 관리·토큰 캐시', state: 'wait' },
    { name: 'M8 멀티 창 표면', scope: '멀티 패널·팝아웃·추가 채팅·btw·토스트·트레이', state: 'wait' },
    { name: 'M-UI 디자인 리뉴얼', scope: '알림/배너 계열 재설계 · 유리 회색 급변 수정 · 디자인 토큰·모던화 (사용자 요청)', state: 'build', round: 1, critic: '유리 원인 규명 → 디자인 시스템 스펙+목업 → 크리틱이 목업을 눈으로 열어 2.6.2와 대조' },
    { name: 'M9 신기능: MCP/Skill 뷰', scope: '멀티채팅 전용 MCP·Skill 가시화', state: 'wait' },
    { name: 'M10 신기능: 세션 간 협업', scope: '클로드 세션 4개 상호 대화 (stash 설계 부활)', state: 'wait' },
    { name: 'M11 신기능: 한도 자동 전환', scope: '소진 시 초기화 임박순 노는 계정 자동 이어가기', state: 'wait' },
    { name: 'M12 패키징+최종 A/B', scope: 'NSIS 대체 설치본·전 화면 대조·최종 인증', state: 'wait' }
  ],
  log: [
    { t: '기준 재정의', m: '사용자 지시로 멀티채팅을 주 게이트로 승격. 2.6.2 멀티 실측: 4패널 유휴 712.8MB → 추가 창 2개 붙이면 934.1MB(창당 110.7MB) → 4패널 동시 스트리밍 직후 1161MB. 렌더링은 여전히 60fps·드랍 0% — 문제는 순전히 메모리' },
    { t: '사용자 요구 추가', m: '알림/배너(모델 자동 전환 등) 디자인 정리 · 사이드바 유리가 진한 회색으로 급변하는 문제 수정 · 전반 모던화 — 3.0 완전 리뉴얼로 반영. 유리 원인 가설: 사이드바는 자체 배경 없이 body 틴트로 아크릴을 비추는 구조라 아크릴이 꺼지면 불투명 회색이 드러남' },
    { t: 'M1 R1 실측', m: '경고 — Tauri 유휴 WS 415.6MB(7프로세스)로 Electron 428MB와 거의 동일, Private는 351 vs 341로 악화. Rust 호스트로 번 85MB를 WebView2가 72MB 더 써서 반납. 메모리 전략 문서로 공격 순서 확정' },
    { t: 'M3 게이트', m: '통과 — 승인 왕복/중단 생존/포크/job object 좀비 차단 실증(크리틱이 대조 재실행·교란변수 제거). 남은 위험: 상주 회계 순서 의존성은 미해소' },
    { t: '판정 인프라', m: '화면 인벤토리 161건 완성(73건 CDP 실도달 검증) → 블라인드 A/B 캡처 하네스 제작 중 (좌우 무작위·정답 키 분리)' },
    { t: '측정', m: '교대 측정기 추가 — 병렬 부하 편향 제거(A/B/A/B 번갈아). tao 16x16 보조 창이 첫 창으로 잡히던 함정 보정' },
    { t: 'M3', m: '와이어 스펙 1563줄 확보(실검증 2회) — CLI 실체는 337MB claude.exe, systemPrompt는 생략해야 프리셋이 산다' },
    { t: 'M0', m: '스트리밍 실측(471항목 전량 렌더 + 실 haiku 턴): 60fps · 드랍 0% · 롱태스크 0ms · 전송→busy 89ms — 성능 승부처는 메모리·콜드 스타트' },
    { t: 'M0', m: '스크롤 실측(471항목): 윈도잉 업스윕 60fps / 전량 렌더 스윕 60fps · 드랍 0%' },
    { t: 'M5 발견', m: '계정 토큰은 Chromium OSCrypt(userData Local State의 DPAPI 키) 암호화 — Rust가 같은 스킴을 읽어야 기존 계정이 재로그인 없이 산다' },
    { t: 'M0', m: '유휴 메모리 실측: WS 428.1MB / Private 341.4MB (5프로세스, 60초 정착)' },
    { t: 'M0', m: '콜드 스타트 실측: 첫 창 336ms / UI 사용 가능 422ms (웜 중앙값 5회) · 진짜 콜드 첫 회 1967/2079ms' },
    { t: '시작', m: '브랜치 feature/3.0.0-beta 생성 · 2.6.2 프로덕션 번들 빌드 완료 · 측정 하네스 작성' }
  ]
}
