window.PROGRESS = {
  phase: 'R16 — 한도 자동 이어서 안전장치 복원(F1 오탐 차단벽·F2 리셋 epoch/재검증) + 렌더러 구독자 구멍(앵커 드리프트·침묵 verdict·user-echo) 병렬 2',
  note: 'R15 착지 — M6 R2: S1~S9 전부 수정(IFileOperation+RECYCLEONDELETE 싱크로 2.6.2와 같은 페일세이프·휴지통 +1 저울 신설 / 비동기 스킴으로 UI 정지 0 / CORS 403 / 잠긴 파일·35MB blob·discard(".") 거절 / 전각·가나 정렬 보정), ccg-fs 73 green / R13·R14 확인: 불일치 0 — 단 신규 6건: ★F1×F2 치명 조합(한도 판정 오탐 3종 + arm_hold가 리셋 epoch 무시·재검증 없음 → 30분 4회 헛 재개 실측, 컨텍스트 초과가 영원히 6.5분마다 재전송 가능 — 2.6.2의 문구 차단벽·2단 판정·발화 재검증이 이식에서 빠짐), F3 앵커 정착 후 365px 드리프트, F4 채팅 폴더 소실=영원한 침묵(verdict 구독자 0), F5 user-echo 구독자 0 → R16 수정 중',
  updatedAt: '2026-08-23 04:20',
  metrics: [
    { name: '★ 멀티 4패널 유휴 WS', unit: 'MB', base: 712.8, new: 421.3, target: '≤356 = WebView2 빈 문서 바닥값(351.5) + 4.5MB — 앱 몫이 47.3이라 구조적 불가, 재협상 대상 (NetSvc2 채택 후 크리틱 실측)', pass: false },
    { name: '★ 멀티 4패널 유휴 Private', unit: 'MB', base: 505.3, new: 239.3, target: '≤253 ✓ (NetSvc2 채택 후 크리틱 실측, 비 0.47)', pass: true },
    { name: '★ 멀티 4패널 + 추가 창 2개 WS', unit: 'MB', base: 934.1, new: 470.9, target: '≤467 — 선상(+3.9)', pass: false },
    { name: '★ 4패널 동시 스트리밍 직후 WS', unit: 'MB', base: 1161, new: null, target: '≤580 (M3 엔진 필요)' },
    { name: '★ 창 1개 추가 비용', unit: 'MB', base: 110.7, new: 25.1, target: '≪110 (+0프로세스, 2.6.2는 +2)', pass: true },
    { name: '★ 멀티 스크롤 FPS', unit: 'fps', base: 60, new: 60, target: '드랍 0% 5/5 유지(1·4패널 모두). avgFps 56~58은 세션 부하 밴드(드랍 프레임 0)', pass: true },
    { name: '★ 렌더러 크래시 복구 (R4 신설·R5 완결)', unit: 'ms', base: null, new: 479, target: '유령 창 0 — 렌더러 ~0.5s·브라우저 1.4s·재kill +3s 573ms·연쇄 1130ms 전 공격 통과, 정상 종료 오인 0, 고아 다이얼로그 정리', pass: true },
    { name: '콜드 첫 픽셀 paintMs (대칭 재측정)', unit: 'ms', base: 423, new: 274, target: '비 0.65 (본 UI끼리 0.79) — R4의 0.45는 비대칭 비교로 반박됨, ≤0.5 승점 아님', pass: false },
    { name: '단일 유휴 메모리 (WS 합)', unit: 'MB', base: 428.1, new: 438.3, target: '≤214 · 주의: 2.6.2 박제값이 오늘 재현 안 됨(626~660) — 분모 신뢰 불가', pass: false },
    { name: '단일 유휴 메모리 (Private 합)', unit: 'MB', base: 341.4, new: 197.2, target: '≤171', pass: false },
    { name: '콜드 스타트 → 첫 창 (웜 중앙값)', unit: 'ms', base: 336, new: 250, target: '≤168 — 구조적 불가(웹 런타임 기동 199~208ms가 하한, Electron도 동일) — 재협상 대상', pass: false },
    { name: '콜드 스타트 → UI 사용 가능', unit: 'ms', base: 422, new: 348, target: '≤211 — 이론 하한 258ms — 재협상 대상', pass: false },
    { name: '긴 스레드 스크롤 평균 FPS (471항목 전량 렌더)', unit: 'fps', base: 60, new: null, target: '≥60' },
    { name: '스트리밍 중 프레임 드랍 (긴 스레드 위)', unit: '%', base: 0, new: null, target: '0' },
    { name: '전송 → 엔진 busy', unit: 'ms', base: 89, new: null, target: '≤89' },
    { name: '설치 풋프린트', unit: 'MB', base: 650, new: null, target: '대폭 감소' }
  ],
  pieces: [
    { name: 'M0 기준 실측', scope: '2.6.2 수치 박제 (콜드 스타트·메모리·스크롤·스트리밍)', state: 'build' },
    { name: 'M1 아키텍처+셸', scope: 'Tauri 워크스페이스·창 시스템·api 심·렌더러 이식 빌드', state: 'build', round: 3, critic: 'R2 성과: 창당 비용 110.7→16.3MB·멀티 유휴 0.64. R3 목표: 유휴 그리드 ≤0.5·콜드 ≤211ms — 레버별 기여도(webview-flags.json) 의무' },
    { name: 'M2 스토리지', scope: 'chats-v3 통합 스토어(보드·status.json)·3스토어 무손실 마이그레이션·api-config/usage(OSCrypt 승계)·talk — CCG_UNIFIED_STORE=1 옵트인, session-wins 별칭이 남아 기본값 미전환', state: 'build', round: 1, critic: '실홈 복사본 바이트 불일치 0·부하 311채팅 1.4s·SIGKILL 안전 — 크리틱이 손상 홈 공격 중' },
    { name: 'M3 Claude 엔진', scope: 'ccg-engine: RunIdentity 3타입·60전이 표·라이브 원장·워치독·claude.exe 드라이버(job object 1커밋)·재생=cargo test', state: 'build', round: 1, critic: '86 테스트 green·필수 재생 27/27·라이브 승인 왕복 933ms — 크리틱이 커버리지 게이트 정직성 공격 중. 남은 것: src-tauri 배선·영속 재장전·O17' },
    { name: 'M4 Codex 엔진+버전 관리', scope: 'app-server JSONL·엔진 설치/업데이트', state: 'wait' },
    { name: 'M5 계정 도메인', scope: '로그인·전환·per-chat 격리·한도 조회 (DPAPI)', state: 'wait' },
    { name: 'M6 파일·Git·뷰어', scope: 'fs ops·git 래퍼·HTML 미리보기 스킴·아이콘', state: 'wait' },
    { name: 'M7 코드 탐색기/LSP', scope: 'TS/JS·Python·C#·C++ (Verse 제외 — 사용자 결정) · 색인·호버·정의이동·자동완성 수치 판정(첫 페인트·p50/p95·프리웜·유휴 회수) · ServerSpec 1항목으로 언어 추가', state: 'wait' },
    { name: 'M-WF 워크플로 카드 effort', scope: '실측 확정: claude.exe 2.1.239 workflow_agent emitter 6개 전수 추출 — effort 없음(fallbackModel은 있음). 세션 effort 대체 표시는 거짓이라 기각. 대안: 모델+fallbackModel 칩 표시(사용자 확인 대기)', state: 'build', round: 1 },
    { name: 'M8 멀티 창 표면', scope: '멀티 패널·팝아웃·추가 채팅·btw·토스트·트레이', state: 'wait' },
    { name: 'M-LOGIC 채팅/실행 상태 정리', scope: 'RunIdentity 단일 값 · 명시적 상태기계 · 설정 변경=명령 · 예약 큐 정체성 스냅샷 · busy 침묵 no-op 제거 · 고아 정착 규약 (사용자 지적: 계정 변경·폴백·특수 상황에서 꼬임)', state: 'build', round: 1, critic: '설계 문서 → M3 빌더가 이 설계로 구현 → 재생 하네스 8조합으로 판정' },
    { name: 'M-UX 채팅 통합', scope: '일반+멀티 → 「채팅」 하나, 개수 다이얼 1~6 (1=기존 레이아웃) · 3스토어/3 IPC 세트 통합 · 무손실 마이그레이션', state: 'build', round: 1, critic: '설계 → 마이그레이션 PoC(손실 0 검증) → 크리틱이 161화면 대조로 기능 누락 사냥' },
    { name: 'M-UI 디자인 리뉴얼', scope: '알림/배너 계열 재설계 · 유리 회색 급변 수정 · 디자인 토큰·모던화 (사용자 요청)', state: 'build', round: 1, critic: '유리 원인 규명 → 디자인 시스템 스펙+목업 → 크리틱이 목업을 눈으로 열어 2.6.2와 대조' },
    { name: 'M9 신기능: MCP/Skill 뷰', scope: '멀티채팅 전용 MCP·Skill 가시화', state: 'wait' },
    { name: 'M10 신기능: 세션 간 협업', scope: '클로드 세션 4개 상호 대화 (stash 설계 부활)', state: 'wait' },
    { name: 'M11 신기능: 한도 자동 전환', scope: '소진 시 초기화 임박순 노는 계정 자동 이어가기', state: 'wait' },
    { name: 'M12 패키징+최종 A/B', scope: 'NSIS 대체 설치본·전 화면 대조·최종 인증', state: 'wait' }
  ],
  log: [
    { t: 'R4 착지', m: 'M1: 크래시 복구 구현·실증(렌더러 479ms/브라우저 1.4s 자동 복구, 대조군은 유령 창 3개 — 블로커 해소. "닫아도 다시 뜨는 앱" 역버그까지 가드 3종+실증). 하네스 결함 6건 수정(앱 몫 8.4→실제 45.6MB 정정, binInfo로 exe 신원 박제, CDP 타임아웃). NetSvc2는 세션 부하로 절대 게이트 판정 불가 → 교대 하네스(fpsab.mjs)로 재판정 중. 콜드 paintMs 공정화: 278 vs 613 = 0.45 승리 공식화 / M-UX R2: 감시자를 렌더러→Rust ChatRuntime으로 이관(접힘 채팅 알림 구멍 근본 해소, 2.6.2의 상위집합 실측)+156화면 사영표 미배정 0(게이트 분모 153)+이중 배선 14갈래 통합법 명시 / M-LOGIC R2: ChatRef 삭제, 워치독 프로브 등급화(프로세스 생존은 Alive 증거 금지), 전이 31→58(와이어 프레임 24행 전수 사영), 재생 8/8 온전(R1: 3/8), 명령표 23×8' },
    { t: 'R4 착수', m: '크리틱 지적 전수 반영 라운드 스폰 — M1: 하네스 결함 6건 수정·NetSvc2 FPS 판정·렌더러 크래시 복구(블로커)·콜드 paintMs 공정화 / M-UX R2: 접힘 채팅 감시 구멍·161화면 파리티 사영표 / M-LOGIC R2: 워치독 P8 자기모순·중단 시 큐 정리·재생 8조합 온전화. chatId 확정(ChatRef 삭제)' },
    { t: '크리틱 판정', m: 'M1 R3: 주장 8건 중 재현 4·부분 3·반박 2 — "앱 몫 8.4MB"는 측정 결함(innerHTML 미해제)으로 반박(실제 43.3MB), Priv 통과 판정도 뒤집힘(10회 중 4회 253 초과, 비 0.504). 신규: 렌더러 크래시=유령 창(전 구성, single-process는 복구 수단 자체가 없음 → 기본값 반대), NetSvc2 발견(프로세스 6→5·WS −37.5), 콜드 paintMs에서 3.0이 0.47배로 이기는데 미보고. 결론: 목표 356은 빈 문서 바닥값(351~387) 선상 — 남은 건 엔지니어링이 아니라 목표·지표 결정. / 설계: 두 스펙 다 보완 — UX 최대 구멍=접힘 채팅 알림 사멸(마커에 상태 없음), LOGIC 최대 구멍=워치독이 P8에서 발화 불가(프로세스 생존 lease 자기모순). 재생 8조합 중 3 불가. chatId 판정(ChatRef 정보량 0비트)' },
    { t: '크리틱 라운드', m: 'M1 R3 실측 크리틱(재현·반박·빠진 레버 사냥·single-process 의사결정표) + 설계 크리틱(인용 전수 검증·기능 구멍 사냥·상태기계 재생 trace·마이그레이션 누락 필드) 병렬 스폰' },
    { t: 'M1 R3 착지', m: '★발견: 4패널 UI를 통째로 지워도 446→438MB — 앱 몫 WS 8.4MB/Priv 24MB, 나머지는 WebView2 바닥값. 렌더러 다이어트는 죽은 길. R2 채택 레버 17개 중 15개 실측 무효(대조군만 차가운 프로필 결함). 채택 2개: --process-per-site(창당 114.7→14.8MB) + --in-process-gpu(Priv 337→252, 프로세스 7→6, 하드웨어 GPU 유지). Priv 목표 통과(0.50)·WS 0.67 미달. 콜드는 구조 하한(기동 202~240ms)으로 ≤168 불가 판정. 옵트인 CCG_SINGLE_PROCESS=1은 전 지표 최고(WS 358.8/Priv 211.3/60fps)지만 MS 미지원이라 기본값 보류 — 사용자 결정 필요' },
    { t: 'M-UX 스펙 R1', m: '「채팅 풀+자리(Slot)+보드」 모델 채택 — 대화는 풀에, 자리는 뷰. 6→1 답: 대화는 아무 데도 안 감(사이드바+접힘 배지+팝오버). 엔진 채널을 slot에서 chatId로, 추가 채팅 창=팝아웃 창=자리를 창으로 뺀 것(owner 한 필드). IPC 55→21. 목업 5장. 열린 문제 10건은 사용자 답변 대기' },
    { t: 'M-LOGIC 설계 R1', m: '9상태·31전이 상태기계(소프트 중단·무음 result 보류·통지 재주입·워치독·정착 전부 전이표의 행으로) + RunIdentity 7필드(정규화 값 하나, resume/fork는 스레드로 분리) + 명령 허용표 19×9 빈칸 없음 + 재생 하네스 8조합 설계. M-UX와 어긋남 1건(ChatRef surface vs chatId) — 크리틱 판정 후 리드가 합침' },
    { t: 'R2 정리·R3 착수', m: 'R2 산출물 6커밋으로 정리(셸: 공유 WebView2 환경+스위치 조립기+주입 스플래시+추가 채팅 창+ma 스토어 / 하네스: ab·blind·flags·heap·wincost / 결과·크리틱 R1·유리 실험대). 3갈래 병렬 스폰: M1 R3(유휴 0.64→0.5·콜드 ≤211) · M-UX 통합 스펙+목업 · M-LOGIC 상태기계 설계' },
    { t: '통합 설계 착수', m: '사용자 아이디어 채택 — 일반/멀티를 「채팅」 하나로 합치고 개수 다이얼 1~6. 1=기존 전체 IDE 레이아웃, 2+=그리드, 1↔N 전환에 대화 보존. 이중 구현(승인 카드·한도 이어서·btw·토스트·계정) 제거가 핵심 이득. 마이그레이션 무손실 PoC 필수' },
    { t: '★ 멀티 성과', m: 'Tauri 멀티 실측 — 창당 비용 110.7MB·+1프로세스 → 16.3MB·+0프로세스(6.8배 개선). 패널4 유휴 712.8→455.5MB(비율 0.64, 목표 0.5 미달로 루프 계속). 스크롤 60fps·드랍 0% 유지' },
    { t: '기준 재정의', m: '사용자 지시로 멀티채팅을 주 게이트로 승격. 2.6.2 멀티 실측: 4패널 유휴 712.8MB → 추가 창 2개 붙이면 934.1MB(창당 110.7MB) → 4패널 동시 스트리밍 직후 1161MB. 렌더링은 여전히 60fps·드랍 0% — 문제는 순전히 메모리' },
    { t: '사용자 요구 추가', m: '알림/배너(모델 자동 전환 등) 디자인 정리 · 사이드바 유리가 진한 회색으로 급변하는 문제 수정 · 전반 모던화 — 3.0 완전 리뉴얼로 반영. 유리 원인 가설: 사이드바는 자체 배경 없이 body 틴트로 아크릴을 비추는 구조라 아크릴이 꺼지면 불투명 회색이 드러남' },
    { t: 'M1 R1 실측', m: '경고 — Tauri 유휴 WS 415.6MB(7프로세스)로 Electron 428MB와 거의 동일, Private는 351 vs 341로 악화. Rust 호스트로 번 85MB를 WebView2가 72MB 더 써서 반납. 메모리 전략 문서로 공격 순서 확정' },
    { t: 'M3 게이트', m: '통과 — 승인 왕복/중단 생존/포크/job object 좀비 차단 실증(크리틱이 대조 재실행·교란변수 제거). 남은 위험: 상주 회계 순서 의존성은 미해소' },
    { t: '판정 인프라', m: '화면 인벤토리 161건 완성(73건 CDP 실도달 검증) → 블라인드 A/B 캡처 하네스 제작 중 (좌우 무작위·정답 키 분리)' },
    { t: '측정', m: '교대 측정기 추가 — 병렬 부하 편향 제거(A/B/A/B 번갈아). tao 16x16 보조 창이 첫 창으로 잡히던 함정 보정' },
    { t: 'M3', m: '와이어 스펙 1563줄 확보(실검증 2회) — CLI 실체는 337MB claude.exe, systemPrompt는 생략해야 프리셋이 산다' },
    { t: 'M0', m: '스트리밍 실측(471항목 전량 렌더 + 실 haiku 턴): 60fps · 드랍 0% · 롱태스크 0ms · 전송→busy 89ms — 성능 승부처는 메모리·콜드 스타트' },
    { t: 'M0', m: '스크롤 실측(471항목): 윈도잉 업스윕 60fps / 전량 렌더 스윕 60fps · 드랍 0%' },
    { t: 'M5 발견', m: '계정 토큰은 Chromium OSCrypt(userData Local State의 DPAPI 키) 암호화 — Rust가 같은 스킴을 읽어야 기존 계정이 재로그인 없이 산다' },
    { t: 'M0', m: '유휴 메모리 실측: WS 428.1MB / Private 341.4MB (5프로세스, 60초 정착)' },
    { t: 'M0', m: '콜드 스타트 실측: 첫 창 336ms / UI 사용 가능 422ms (웜 중앙값 5회) · 진짜 콜드 첫 회 1967/2079ms' },
    { t: '시작', m: '브랜치 feature/3.0.0-beta 생성 · 2.6.2 프로덕션 번들 빌드 완료 · 측정 하네스 작성' }
  ]
}
